#!/bin/bash
# This script must be run in GNU/Linux OR in DOS/DJGPP Bash shell.

RM='rm -f'

cleandir() {
    local DIR="$1"
    echo "Cleaning $DIR ..."
    cd $DIR
    $RM *.err
    $RM *.exe
    $RM *.map
    $RM *.obj
    $RM *.tpu
    cd $OLDPWD
}

cleandir ./src/cc
cleandir ./src/cc/conio
$RM ./src/cc/conio/inp.asm
$RM ./src/cc/conio/outp.asm
cleandir ./src/cc/ctype
$RM ./src/cc/ctype/istable.asm
cleandir ./src/cc/errno
$RM ./src/cc/errno/errno.asm
cleandir ./src/cc/i86
$RM ./src/cc/i86/delay.asm
$RM ./src/cc/i86/disable.asm
$RM ./src/cc/i86/enable.asm
cleandir ./src/cc/string
$RM ./src/cc/string/memcmp.asm
$RM ./src/cc/string/memcpy.asm
$RM ./src/cc/string/memset.asm
$RM ./src/cc/string/strchr.asm
$RM ./src/cc/string/strcmp.asm
$RM ./src/cc/string/stricmp.asm
$RM ./src/cc/string/strlen.asm
$RM ./src/cc/string/strncmp.asm
$RM ./src/cc/string/strncpy.asm
$RM ./src/cc/string/strnicmp.asm
cleandir ./src/hw
$RM ./src/hw/dma.asm
$RM ./src/hw/pic.asm
$RM ./src/hw/sndctl_t.asm
cleandir ./src/hw/sb
$RM ./src/hw/sb/detisr.asm
$RM ./src/hw/sb/sbctl.asm
$RM ./src/hw/sb/sbio.asm
$RM ./src/hw/sb/sndisr.asm
cleandir ./src/dos
$RM ./src/dos/emstool.asm
cleandir ./src/main
$RM ./src/main/effects.asm
$RM ./src/main/filldma.asm
$RM ./src/main/fillvars.asm
$RM ./src/main/loads3m.asm
$RM ./src/main/mixer.asm
$RM ./src/main/mixing.asm
$RM ./src/main/mixvars.asm
$RM ./src/main/posttab.asm
$RM ./src/main/readnote.asm
$RM ./src/main/s3mplay.asm
$RM ./src/main/s3mvars.asm
$RM ./src/main/voltab.asm
cleandir ./src/ow
$RM ./src/ow/dos_.asm
$RM ./src/ow/malloc.asm
$RM ./src/ow/printf.asm
$RM ./src/ow/stdio.asm
$RM ./src/ow/stdlib.asm
cleandir ./src/pascal
cleandir ./src/player

echo "Done."
