#!/bin/bash
# This script must be run in GNU/Linux OR in DOS/DJGPP Bash shell.

cleandir() {
    local DIR="$1"
    echo "Cleaning $DIR ..."
    cd $DIR
    rm -f *.err
    rm -f *.exe
    rm -f *.map
    rm -f *.obj
    rm -f *.tpu
    cd $OLDPWD
}

cleandir ./src/cc
cleandir ./src/cc/i86
rm -f ./src/cc/i86/delay.asm
rm -f ./src/cc/i86/disable.asm
rm -f ./src/cc/i86/enable.asm
cleandir ./src/hw
rm -f ./src/hw/dma.asm
rm -f ./src/hw/pic.asm
rm -f ./src/hw/sndctl_t.asm
cleandir ./src/hw/sb
rm -f ./src/hw/sb/detisr.asm
rm -f ./src/hw/sb/sbctl.asm
rm -f ./src/hw/sb/sbio.asm
rm -f ./src/hw/sb/sndisr.asm
cleandir ./src/dos
rm -f ./src/dos/emstool.asm
cleandir ./src/main
rm -f ./src/main/effects.asm
rm -f ./src/main/filldma.asm
rm -f ./src/main/fillvars.asm
rm -f ./src/main/loads3m.asm
rm -f ./src/main/mixer.asm
rm -f ./src/main/mixing.asm
rm -f ./src/main/mixvars.asm
rm -f ./src/main/posttab.asm
rm -f ./src/main/readnote.asm
rm -f ./src/main/s3mplay.asm
rm -f ./src/main/s3mvars.asm
rm -f ./src/main/voltab.asm
cleandir ./src/ow
rm -f ./src/ow/dos_.asm
rm -f ./src/ow/malloc.asm
rm -f ./src/ow/printf.asm
rm -f ./src/ow/stdio.asm
rm -f ./src/ow/stdlib.asm
cleandir ./src/pascal
cleandir ./src/player

echo "Done."
