#!/bin/bash
# This script must be run in GNU/Linux.
# Packages used: coreutils, grep, dos2unix.

set -e
. ./common.shlib
. ./setup.conf

if [ ! -f "$SYS_DOSEMU_CONF" ]; then
    cat <<EOF > "$SYS_DOSEMU_CONF"
\$_ems_frame = (0xe000)
\$_sound = (2)
EOF
    echo_info "Created '$SYS_DOSEMU_CONF' file."
else
    echo_warn "Skip: File '$SYS_DOSEMU_CONF' already exists."
fi

if [ ! -f "$ENV_PROJECT_INIT" ]; then
    cat <<EOF | unix2dos > "$ENV_PROJECT_INIT"
@echo off
call $DOS_DJGPP_INIT
call $DOS_WATCOM_INIT
call $DOS_TP_INIT
cd $DOS_PROJECT_DIR
${DOS_PROJECT_DIR:0:2}
EOF
    echo_info "Created '$ENV_PROJECT_INIT' file."
else
    echo_warn "Skip: File '$ENV_PROJECT_INIT' already exists."
fi

if ! dos2unix < "$ENV_DRIVE_C_DIR/autoexec.bat" | grep -F -x "call $DOS_PROJECT_INIT" >/dev/null; then
    cat <<EOT | unix2dos >> "$ENV_DRIVE_C_DIR/autoexec.bat"
call $DOS_PROJECT_INIT
EOT
    echo_info "Updated '$ENV_DRIVE_C_DIR/autoexec.bat' file."
else
    echo_warn "Skip: File '$ENV_DRIVE_C_DIR/autoexec.bat' already updated."
fi

echo_info 'DOSEMU setup is finished.'
