#!/bin/bash
# This script must be run in GNU/Linux.
# Packages used: coreutils, dos2unix.

set -e
. ./common.shlib
. ./setup.conf

if [ ! -e "$ENV_TP_DIR" ]; then
    echo_warn "Error: You must manually install TP into '$ENV_TP_DIR' directory."
    exit 1
else
    echo_warn "Skip: Target '$ENV_TP_DIR' already exists."
fi

if [ ! -f "$ENV_TP_INIT" ]; then
    cat <<EOF | unix2dos > "$ENV_TP_INIT"
@echo off
set PATH=%PATH%;$DOS_TP_DIR\\bin
EOF
    echo_info "Created '$ENV_TP_INIT' file."
else
    echo_warn "Skip: File '$ENV_TP_INIT' already exists."
fi

echo_info 'TP setup is finished.'
